---
- name: Create Portainer Module 
  hosts: masters
  remote_user: root
  become: true
  environment:
    LANGUAGE: en_US.UTF-8
    LC_ALL: fr_FR.utf-8
  roles:
    -  { role: cloudera_manager_install }