---
  - name: include task config 
    include: config.yml
    
  - name: Install Cloudera Manager Packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - cloudera-manager-agent
      - cloudera-manager-daemons
      - cloudera-manager-server

  - name: Start Cloudera Manager Server
    service:
      name: cloudera-scm-server
      state: started
      enabled: yes
    when: cloudera_manager_node == 'master1'
